# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://dropfl.github.io # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : /blog # does not include hostname
title   : DropFL's Blog
description: > # this means to ignore newlines until "Language & timezone"
  Blog about programming & computer science things.


## => Language and Timezone
##############################
lang: ko # the language of your site, default as "en"
timezone: Asia/Seoul # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : person
  name      : DropFL
  url       : # TODO
  avatar    : https://avatars2.githubusercontent.com/u/18409052
  bio       : I am... # TODO
  email     : dnjsah1230@gmail.com
  medium    : "@dropfl"
  github    : DropFL


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: DropFL/blog
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true
mathjax_autoNumber: false

## Mermaid
mermaid: true

## Chart
chart: true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: bootcdn # or unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"


## => Comments
##############################
comments:
  # false (default), "disqus", "gitalk", "valine", "custom"
  provider: disqus

  disqus:
    shortname: dropfl-blog


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - LICENSE
  - "*-README.md"
  - README.md
  - /screenshots

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji